### ISSUE TITLE
append_many_to_dataset: Mutation "data" failed with error: unknown field

### ISSUE THREAD

**Issue by rth** [kili-technology/kili-playground#179]
I'm currently trying to add some data in an NLP project via the API with,
```py
      playground.append_many_to_dataset(project_id=project_id,
                                        content_array=['test document 1'],
                                        external_id_array=['doc1'])
```

this fails with,
```
  File "kili\mutations\asset\__init__.py", line 61, in append_many_to_dataset
    projects = playground.projects(project_id)
  File "kili\queries\project\__init__.py", line 68, in projects
    return format_result('data', result)
  File "kili\helpers.py", line 17, in format_result
    raise GraphQLError(name, result['errors'])
kili.helpers.GraphQLError: Mutation "data" failed with error: "[{'message': 'unknown field', 'path': ['variable', 'where', 'updatedAtGte'], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]"
```

it turns out that just running `playground.projects(project_id)` produced the same error. I noticed that providing a random `project_id` will also produce the same error. So at this point I have 2 hypothesis,
 - either that error is just an indication that the project_id is incorrect. I'm using the ID from the URL e.g. `/label/projects/<project_id>`. If it is incorrect is there another way I can find it?
 - or there is an unrelated issue with this project somewhere.

Suggestions how to debug this would be very much appreciated. Thanks!

**Comment by marcenacp** [comment]
Hello @rth,

- You are correct when you derive the project ID from `/label/projects/<project_id>`.
- This seems like a generic GraphQL error. Do you use the latest version of Kili? Can you run `pip uninstall kili` and pip install kili==2.0.7`?

Thanks for your answer!

**Comment by rth** [comment]
Thanks @marcenacp ! Yes, I have the latest version of the kili package,
```
$ pip list | grep kili
kili                          2.0.7
```
and I don't think there are installation issues. I have previously created a project via the API and it worked fine. Actually uploading the files and labeling via the UI also works fine, the issue is only for uploading assets via the API as far as I can tell.

It doesn't seem related to the project definition either, I just created a simple multi-class text classification project and I also see this issue when calling `playground.projects(project_id)`.

**Comment by mDuval1** [comment]
Hi @rth , 
If uninstalling _then_ reinstalling kili still does not work for you, I sent you a call invite to help you with this issue. Tell me if the time suits you.
Maxime

**Comment by rth** [comment]
Actually downgrading to `kili==2.0.4` appears to work for my case. Maybe the version of the server is outdated, I wasn't able to determine that from the UI. Interestingly with 2.0.4 I get,
```
kili\authentication.py:54: UserWarning: Kili Playground version should match with Kili API version.
Please install version: "pip install kili==2.0.2"
```
while there are no such warnings with 2.0.7. Anyway I'm closing this as resolved, thanks for your help!
