### ISSUE TITLE
More detailed changelog for breaking changes

### ISSUE THREAD

**Issue by rth** [kili-technology/kili-playground#184]
It would be helpful to have a more detailed changelog (ideally as a file in this repository) that would in particular mention breaking changes. 

For instance, with 2.0.4 I have a script that worked fine to create a new project with,
```
    json_interface = {
        "filetype": "TEXT",
        "jobs": {  .... }
    }
```
(adapted from a documentation example).
In 2.1.1 this same script produces the following error,
```
kili.helpers.GraphQLError: Mutation "data" failed with error: "[{'message': '[unsupportedType] Unsupported project input type "NA". Input type should be one of: IMAGE, PDF, TEXT, VIDEO', 'path': ['data']}]"
```
presumably because the input type now needs to be specified via the `input_type` parameter of `update_properties_in_project` (related to https://github.com/kili-technology/kili-playground/pull/160)

This is a breaking change and it would help if was explicitly specified in the release notes, so one wouldn't have to search through the source code or the the commit history as to what needs to be changed.

**Comment by p-desaintchamas** [comment]
Hello @rth, 

We do publish a changelog, on this page https://cloud.kili-technology.com/docs/changes/change-log/. 

In particular, the change you are referring to is documented here https://cloud.kili-technology.com/docs/changes/change-log/#change-1. We try to update the documentation examples as much as possible, and deeply regret that you did not find accurate information. Don't hesitate to reach out when a documentation script is outdated.

Have a nice day,

**Comment by rth** [comment]
> We do publish a changelog, on this page

Aww great, sorry I missed that. It could be helpful to mention it in some way in the readme.

> In particular, the change you are referring to is documented here

Right, but that entry says,

>> APP : JSON interface has been simplified and Filtetype key has been removed

it doesn't say what I as an existing user should change in my code as a result of this removal. Otherwise thanks for keeping a changelog!
