### ISSUE TITLE
Warning: labelOf { externalId } must be an instance of <enum 'Label'>

### ISSUE THREAD

**Issue by rth** [kili-technology/kili-playground#194]
I'm trying to get the `externalId` of assets associated to a label when calling  https://cloud.kili-technology.com/docs/python-graphql-api/python-api/#labels

Initially I tried,
```py
>>> labels = playground.labels(project_id=project_id,  fields=['id', 'labelOf'])
```
which produces,
```py
  File "lib\site-packages\kili\queries\label\__init__.py", line 126, in labels
    return format_result('data', result)
  File "lib\site-packages\kili\helpers.py", line 17, in format_result
    raise GraphQLError(name, result['errors'])
kili.helpers.GraphQLError: Mutation "data" failed with error: "[{'message': 'Field "labelOf" of type "Asset" must have a selection of subfields. Did you mean "labelOf { ... }"?', 'locations': [{'line': 4, 'column': 47}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}]"
```

So indeed if I change as suggested,
```py
>>> labels = playground.labels(project_id=project_id,  fields=['id', 'labelOf  { externalId }'])
```
this works as expected, however I now get the following message on stdout
```
labelOf { externalId } must be an instance of <enum 'Label'>
```
printed [here](https://github.com/kili-technology/kili-playground/blob/69aa630fae5c7670657e53d6a3dace06fb2291d1/kili/helpers.py#L80).  Because it's not a warning but a print I cant silence it either.

The returned results are correct and include the "externalId", so it's not a big issue, but it would be nice to be able to silence this message.

**Comment by marcenacp** [comment]
Hi Roman,

We have to allow cross-referenced types (labels can extend an asset via `labels`, and assets can extend a label via `labelOf`). We just opened #195 that will fix this warning.

The proper syntax will then be:

```
fields=['id', 'labelOf.externalId', ...]
```

We'll keep you posted once the merge requested gets accepted.

Thanks,
Pierre
