### ISSUE TITLE
Max. length of text documents?

### ISSUE THREAD

**Issue by mawic** [kili-technology/kili-playground#377]
Hi,
I want to use your platform to annotate text documents. But after uploading the txt files, not the entire text document is displayed. It seems to cut each document after 200 lines (+- depending on the file). Is there a specific limit for txt files?

Thanks,
Max

**Comment by mDuval1** [comment]
Hi Max,

There are no limits for txt files. We had an issue on the parsing of text files, thank you for spotting it !
A fix should come soon.

Regards,

Maxime

**Comment by mawic** [comment]
Thanks! When will you release the fixed version? We would like to use it
for a larger annotation task in the next days.  Best,
Max

Maxime Duval ***@***.***> schrieb am Di. 29. Juni 2021 um
17:40:

**Comment by mDuval1** [comment]
The fix should be deployed now.

Best,
Maxime

**Comment by mawic** [comment]
It works! Thanks!
