### ISSUE TITLE
Allow to edit the boundary box

### ISSUE THREAD

**Issue by Akronix** [kili-technology/kili-playground#502]
Allow to edit the boundary box once it's created in order to adjust more precisely to the object and remove margins.

**Comment by theodu** [comment]
Hi @Akronix 
Once a bounding box is created on the image, you can click on your bounding box to select it. When it is selected, dots appear on the edge of the bounding box. You can grab and move these edges to change the size of the bounding box. 
You can also click on the middle of the box to move it or click on the arrows and make it turn.
You can find a tutorial video on this page in our documentation : https://cloud.kili-technology.com/docs/interfaces-image/bounding-box/

**Comment by Akronix** [comment]
I couldn't see the option previously, but now I does display and I can edit.
Thanks.
